### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [MaxPat931/D-n-D-Friends-Guilds#1]
**Submitted By**: MaxPat
**Feedback Type**: Enhancement
 
**Core:** 9.255
**System:** dnd5e v1.5.7
**Module Version:** d-n-d-friends-guilds v1.8
**Dependency Version:** Compendium Folders v2.4.3
 
**Description**:
This is a test
The Second Wind Feature should be set to 1d10+fighter levels<details>
<summary>Module Settings</summary>

```js

```
</details>
<details>
<summary>Active Modules</summary>

arbron-context-menus--v0.2.2;
bug-reporter--v1.3.3;
compendium-folders--v2.4.3;
compendium-tools--v0.4.4;
d-n-d-friends-guilds--v1.8;
dae--v0.9.12;
ddb-importer--v2.9.17;
dice-so-nice--v4.5.0;
lib-wrapper--v1.12.4.0;
roll-from-compendium--v1.2.4;
socketlib--v1.0.10;
</details><details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by MaxPat931** [comment]
Test complete! cool beans
